---

- name: create group
  group:
    name: "{{ prometheus_group }}"
    system: true
    state: present

- name: create user
  user:
    name: "{{ prometheus_user }}"
    system: true
    shell: "/sbin/nologin"
    group: "{{ prometheus_group }}"
    createhome: false
    home: "{{ prometheus_dirs.data }}"

- name: create data directory
  file:
    path: "{{ prometheus_dirs.data }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755

- name: create configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ prometheus_group }}"
    mode: 0770
  with_items:
    - "{{ prometheus_dirs.config }}"
    - "{{ prometheus_dirs.config }}/rules"
    - "{{ prometheus_dirs.config }}/targets"

- name: download archive to local folder
  become: false
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: extract archive
  become: false
  unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
  delegate_to: localhost
  check_mode: false

- name: copy binaries
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - prometheus
    - promtool
  notify:
    - restart prometheus service
