---

- name: gather required facts
  setup:
    gather_subset: [min]
  when: ansible_distribution_release is not defined

- name: install
  include_tasks: install.yml
  when: prometheus_setup == "full" or prometheus_setup == "install"

- name: configure
  import_tasks: configure.yml
  when: prometheus_setup == "full" or prometheus_setup == "configure"
